### ISSUE TITLE
Director mode not working.

### ISSUE THREAD

**Issue by momokrono** [edyoung/gnofract4d#7]
First of all, great software!
The issue I'm reporting is related to the director mode:
I've imagemagick and transcode installed and compiled, but every time i try to render a video it ends up with nothing:
I can see the render screen working, but when it reaches the end nothing happend.
The thing is that i've tryied to modify the directory for tmp images and i can see that pictures are rendered but when all are done the program doesn't produce any video.
Also i cannot see any output file called like "render.avi" but instead only an "animation.fcta".
Plus i cannot write inside the space to select a name to my new animation, i can just select a file from "browse", and even creating an empty file called "animation.avi" and selecting it i end up with nothing but a bunch of pictures.

**Comment by edyoung** [comment]
Thanks for the report. The director code depends a lot on external programs and hasn't been touched in quite a while. I will take a look when i can.

If you have all the individual frames, it may be possible to stitch them together using a suitable package outside of gnofract4d.

**Comment by momokrono** [comment]
Thank you for the reply!
Actually i'm fine having all the frames anyway, and it's not so much an effort convert those into a video.
2 other thing that i've noticed are that when selecting 8 threads (i have an i7) the program crashes, thing that doesn't happen keep the number of threads low.
Also i cannot increase the number of iterations as long as i want, and after a while i reach a zoom level while i don't have a smooth image, pressing the button to double the iterations or increasing those into the setting area is useless :\

**Comment by edyoung** [comment]
The 'number of threads' thing is interesting, will have to see if I can reproduce that.

Number of iterations != precision. 

The issue with zooming is expected and due to the limits of precision offered by processors' floating point implementation. Basically processors don't do exact math, but round things off after 53 binary bits of precision ('double precision'). In most situations that's fine, but in a fractal after you have zoomed in far enough, it's not enough to clearly represent the image, and you start seeing a messed-up image. Some fractal packages provide an 'arbitrary precision' mode which can zoom further at the cost of slowing things down quite a lot, but unfortunately I've not had time to implement that.

**Comment by momokrono** [comment]
Thanks for the explanation!
Basically giving to all the variables involved into the computation of a certain color in the picture more that 52 bits at the fraction part should solve the zoom issue, but at the cost of having variables longer than 64 bits with the slowdowns in computing, right?
If it's so i'll try to find a solution by myself.
Anyway I'll keep using this program, and i'll write here if i'll found something new.

**Comment by edyoung** [comment]
I haven't explicitly checked all the issues raised, but was able to generate a video successfully. Please open a new issue if you can still see this using python3 branch
